import { z } from 'zod';
import { tradingStatusSchema } from '../auction-common/auction-common.schemas';
import {
  auctionListAuctionTypeFilterSchema,
  dateTimeWithOffsetSchema,
} from './auction-list.schemas';

export const auctionListSearchSchema = z.object({
  page: z.number().int().optional(),
  perPage: z.number().int().optional(),
  isOldest: z.boolean().optional(),
  sort: z
    .record(z.string(), z.enum(['asc', 'desc']))
    .nullable()
    .optional(),
  status: z.array(tradingStatusSchema).optional(),
  mobileStatuses: z.array(z.number().int()).optional(),
  statuses: z.array(z.number().int()).optional(),
  cargoNum: z.string().optional(),
  weightFrom: z.number().optional(),
  weightTo: z.number().optional(),
  volumeFrom: z.number().optional(),
  volumeTo: z.number().optional(),
  bodyTypes: z.array(z.string()).optional(),
  formType: z.string().nullable().optional(),
  isInternationalShipment: z.boolean().optional(),
  loadCity: z.string().optional(),
  loadGcId: z.number().int().optional(),
  loadRange: z.number().int().optional(),
  unloadCity: z.string().optional(),
  unloadGcId: z.number().int().optional(),
  unloadRange: z.number().int().optional(),
  loadDateFrom: dateTimeWithOffsetSchema.optional(),
  loadDateTo: dateTimeWithOffsetSchema.optional(),
  unloadDateFrom: dateTimeWithOffsetSchema.optional(),
  unloadDateTo: dateTimeWithOffsetSchema.optional(),
  createDateFrom: dateTimeWithOffsetSchema.optional(),
  createDateTo: dateTimeWithOffsetSchema.optional(),
  startTimeFrom: dateTimeWithOffsetSchema.optional(),
  startTimeTo: dateTimeWithOffsetSchema.optional(),
  stopTimeFrom: dateTimeWithOffsetSchema.optional(),
  stopTimeTo: dateTimeWithOffsetSchema.optional(),
  isAvailable: z.boolean().optional(),
  isFavorite: z.boolean().optional(),
  isBidder: z.boolean().optional(),
  customer: z.string().optional(),
  customerIds: z.array(z.number().int()).optional(),
  contractor: z.string().nullable().optional(),
  auctionIds: z.array(z.number().int()).optional(),
  replaceExternalPads: z.boolean().nullable().optional(),
  currentPriceFrom: z.number().nullable().optional(),
  currentPriceTo: z.number().nullable().optional(),
  pricePerKmFrom: z.number().nullable().optional(),
  pricePerKmTo: z.number().nullable().optional(),
  auctionTypes: z.array(auctionListAuctionTypeFilterSchema).optional(),
});
